export const ERROR = 'ERROR';

export const USER_LOADING = 'USER_LOADING';
export const USER_NONE = 'USER_NONE';
export const USER_LOADED = 'USER_LOADED';

export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_LOADED = 'COMMENTS_LOADED';

export const COMMENT_SAVING = 'COMMENT_SAVING';
export const COMMENT_SAVED = 'COMMENT_SAVED';

export const OCTOMMENTS_USER = 'OCTOMMENTS_USER';

export const CONSTANTS = [
  ERROR,
  COMMENTS_LOADING,
  COMMENTS_LOADED,
  COMMENT_SAVING,
  USER_LOADING,
  USER_NONE,
  USER_LOADED,
  COMMENT_SAVED,
];
