export const LOADING_COMMENTS = 'LOADING_COMMENTS';
export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const COMMENTS_ERROR = 'COMMENTS_ERROR';
export const USER_ERROR = 'USER_ERROR';
export const LOADING_CURRENT_USER = 'LOADING_CURRENT_USER';
export const NO_USER = 'NO_USER';
export const USER_LOADED = 'USER_LOADED';
export const SAVING_COMMENT = 'SAVING_COMMENT';
export const COMMENT_SAVED = 'COMMENT_SAVED';
export const COMMENT_ERROR = 'COMMENT_ERROR';

export const OCTOMMENTS_USER = 'OCTOMMENTS_USER';
